### ISSUE TITLE
Improvement suggestion

### ISSUE THREAD

**Issue by gioragutt** [sindresorhus/is-array-sorted#3]
Don't wanna go so far as to PR, but:
```typescript
'use strict';
module.exports = (arr, comp) => {
	for (let i = 0; i < arr.length - 1; i++) {
		const a = arr[i];
		const b = arr[i + 1];

		if (comp ? comp(a, b) > 0 : a > b) {
			return false;
		}
	}

	return true;
};
```
to
```typescript
'use strict';
module.exports = (arr, comp) => {
        const compare = comp
            ? (a, b) => comp(a, b) > 0
            : (a, b) => a > b;
	for (let i = 0; i < arr.length - 1; i++) {
		const a = arr[i];
		const b = arr[i + 1];

		if (compare(a, b)) {
			return false;
		}
	}

	return true;
};
```
doesn't have to do the comparison method `?:` every iteration

**Comment by sindresorhus** [comment]
I have a feeling this will be slightly slower, as you're introducing a function call for each iteration where there didn't use to be one, in the common case of not using a custom comparator. Might not matter, but that really depends on how smart V8 is these days. I don't really have the time to benchmark, so I'm gonna close this as it only minimally improves the readability, but potentially makes it slower.
